# Generated by Selenium IDE
import os
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# driver = webdriver.Chrome(executable_path=".\chromedriver.exe")
driver = webdriver.Edge(executable_path=".\msedgedriver.exe")
vars = {}

driver.get("https://openspeedtest.com/")
driver.set_window_size(945, 1020)
WebDriverWait(driver, 30000).until(expected_conditions.visibility_of_element_located((By.XPATH, "//*[name()='use' and @*='#playButton']")))
elem = driver.find_element_by_xpath("//*[name()='use' and @*='#playButton']")
ac = ActionChains(driver)
ac.move_to_element(elem).move_by_offset(0,0).click().perform()

runningtest = True
downloadspeed = '---'
uploadspeed = '---'

print('Test is running...')
while runningtest:
    WebDriverWait(driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "downResult")))
    WebDriverWait(driver, 30000).until(expected_conditions.visibility_of_element_located((By.ID, "upRestxt")))

    downloadspeed = driver.find_element(By.ID, "downResult").text
    uploadspeed = driver.find_element(By.ID, "upRestxt").text

    time.sleep(1)

    if downloadspeed != '---':
        if uploadspeed != '---':
            runningtest = False

print('Download Speed: {}'.format(downloadspeed))
print('Upload Speed:   {}'.format(uploadspeed))

driver.quit()
